[package]
name = "kalkoto-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.24", features = ["derive"] }
crossterm = "0.28.1"
kalkoto-lib = { path = "../kalkoto-lib" }
